"""feat: update models and add categories reviews

Revision ID: 220beed3b601
Revises: acc8ae75f9e8
Create Date: 2025-12-05 23:19:47.272619

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '220beed3b601'
down_revision: Union[str, Sequence[str], None] = 'acc8ae75f9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('book_categories',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_categories_book_id_books')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_book_categories_category_id_categories')),
    sa.PrimaryKeyConstraint('book_id', 'category_id', name=op.f('pk_book_categories'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('book_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reviews_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    
    # 1. DEFINIMOS Y CREAMOS EL ENUM MANUALMENTE
    loan_status = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')
    loan_status.create(op.get_bind())
    
    
    
    op.add_column('books', sa.Column('stock', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=False))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    
    # 2. AHORA SÍ AGREGAMOS LA COLUMNA USANDO EL ENUM CREADO
    op.add_column('loans', sa.Column('status', loan_status, nullable=False, server_default='ACTIVE'))
    
    op.add_column('loans', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    
    
    
    #op.add_column('loans', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus'), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('loans', 'status')
    
    loan_status_enum = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')
    loan_status_enum.drop(op.get_bind())
    
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language')
    op.drop_column('books', 'description')
    op.drop_column('books', 'stock')
    op.drop_table('reviews')
    op.drop_table('book_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
